# Generated by Django 4.1.7 on 2023-04-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_seats', models.CharField(default='1A,1B,1C,1D,1E,1F,1G,2A,2B,2C,2D,2E,2F,2G,...,10E,10F,10G', max_length=200)),
                ('booked_seats', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
